apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: plcnvf5na-python 
  janus-idp.io/tekton: plcnvf5na-python
  backstage.io/kubernetes-id: plcnvf5na-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: plcnvf5na-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  