apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: plcnvf5na-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: plcnvf5na-python 
  name: plcnvf5na-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: plcnvf5na-python
    weight: 100 
