apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: plcnvf5na-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: plcnvf5na-python 
  name: plcnvf5na-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: plcnvf5na-python 
